---
name: rails-settings-cached
version: 0.6.5
type: bundler
summary: Settings plugin for Rails that makes managing a table of global keys.
homepage: https://github.com/huacnlee/rails-settings-cached
license: none
licenses: []
notices: []
